//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplomski
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int ID_event { get; set; }
        public string place { get; set; }
        public Nullable<System.DateTime> date_in { get; set; }
        public Nullable<System.DateTime> date_out { get; set; }
        public Nullable<int> tag_ID { get; set; }
        public string reason { get; set; }
    }
}
