//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplomski
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int ID_tag { get; set; }
        public string tag1 { get; set; }
        public string name { get; set; }
    }
}
